# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

## Orals
[[main]]
  name = "Oral"
  pageRef = "oral"
  weight = 11

[[main]]
  name = "(o) AI Applications"
  parent = "Oral"
  pageRef = "oral-ai-applications"

[[main]]
  name = "(o) AI Theory"
  parent = "Oral"
  pageRef = "oral-ai-theory"

[[main]]
  name = "(o) Large Language Models"
  parent = "Oral"
  pageRef = "oral-large-language-models"

[[main]]
  name = "(o) Reinforcement Learning"
  parent = "Oral"
  pageRef = "oral-reinforcement-learning"

[[main]]
  name = "(o) Image Generation"
  parent = "Oral"
  pageRef = "oral-image-generation"

[[main]]
  name = "(o) Others"
  parent = "Oral"
  pageRef = "oral-others"


## Spotlight
[[main]]
  name = "Spotlight"
  pageRef = "spotlight"
  weight = 22

[[main]]
  name = "(s) AI Theory"
  parent = "Spotlight"
  pageRef = "spotlight-ai-theory"

[[main]]
  name = "(s) Large Language Models"
  parent = "Spotlight"
  pageRef = "spotlight-large-language-models"

[[main]]
  name = "(s) Reinforcement Learning"
  parent = "Spotlight"
  pageRef = "spotlight-reinforcement-learning"

[[main]]
  name = "(s) Optimization"
  parent = "Spotlight"
  pageRef = "spotlight-optimization"

[[main]]
  name = "(s) Others"
  parent = "Spotlight"
  pageRef = "spotlight-others"

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 88

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.